### ISSUE TITLE
Fix rabbitmq collector metrics blacklist

### ISSUE THREAD

**Issue by rclag1126** [Netuitive/omnibus-netuitive-agent#38]

**Comment by TheConnMan** [comment]
What problem was happening that your PR fixes?

**Comment by rclag1126** [comment]
The blacklist wasn't _actually_ blacklisting the `queues.*` metrics. I suspect it's because "rabbitmq" was included in the original regex, which isn't needed

**Comment by TheConnMan** [comment]
Ah, that is unfortunate. Thanks for the explanation.

**Comment by dgeorg42** [comment]
Just to add some color to this - at some point I had moved the generation of the first part of the metric name (the part which identifies the collector, i.e., "rabbitmq") to a different part of the code so that it could be overridden in the config file. The reason for this is that we wanted to be able in the Cassandra metrics to replace "jolokia" with "cassandra" (and similarly for Kafka). As a result of that change, the collector portion of the metric name isn't added until _after_ the blacklist/whitelist filtering happens. So after that change, the "rabbitmq" in the regex wasn't needed any longer, but clearly I missed going back and updating it.
